oscafrica/osf-website

.github/FUNDING.yml, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .gitignore, CONTRIBUTING.md, README.md, package-lock.json, package.json
Setup Commitizen command utility tool
- Install and configure Commitizen for this project
- Update the contributor's guide to explain how to use Commitizen
- Update the README.md to further explain how to access the contributor's guide
- Install and configure Open Collective CLI tool
- Setup Open Collective badges
When you commit with Commitizen, you'll be prompted to fill out any required commit fields at commit time.
You can achieve this by running `npm run commit` instead of `git commit`
N/A
N/A
=> chore(commitizen): Install and configure commitizen

src/pages/tailwind-config-demo.js, tailwind.config.js
Set up the workflow of using Tailwind with our components and overriding Tailwind default properties.
Also create a demo page that shows how to use the custom classes.
Override the default styling properties provided by tailwind css, add custom styles based on the 
[styleguid](https://www.figma.com/file/wtojDaoY2PJED946ZMIvsX/OSCA-style-guide%2Fpattern) provided. create a demo page to show how generated custom classes can be used
1. checkout this branch
2. run `npm run i` & `npm run develop`
3 visit `http://localhost:8000/tailwind-demo-page` when development server has started
4. open `tailwind.config.js` file to see the changes made and open `tailwind-config-demo.js` under pages folder to see how custom classes are used
#2
no
#2
=> chore(tailwind.config.js): set up tailwind config workflow

.editorconfig, .github/PULL_REQUEST_TEMPLATE.md, .storybook/config.js, .storybook/webpack.config.js, README.md, package-lock.json, package.json, src/components/button/button.stories.js, src/components/button/index.js, src/components/button/style.module.css, src/pages/about.js
Create the Button component (Style Guide Components)
* Configure and Install storybook for this project
* Add a PULL REQUEST template for contributions
* Add `.editorconfig` for automatic linting.
* Create a reusable button component according to the [style guide](https://www.figma.com/file/wtojDaoY2PJED946ZMIvsX/OSCA-style-guide%2Fpattern?node-id=0%3A1).
By opening up the storybook and viewing the button component.
The storybook can be stated with the command `yarn storybook` or `npm run storybook`
[#14](https://github.com/oscommunityafrica/osf-website/issues/14)
N/A
=> #14 Create the Button component (Style Guide Components)

CONTRIBUTING.md
Fixes typo on Github Issues URL.
Fix broken URL `websit` -> `website`
#<NUMBER>
=> chore(CONTRIBUTING.md): fix typo.

src/components/pagination/index.js, src/components/pagination/pagination.stories.js, src/components/pagination/style.module.css, src/components/tab/Tabs.js
Waiting for @perriefidelis on the interaction
Implemented Google's implementation
Add the pagination component as in the [style guide](https://www.figma.com/file/wtojDaoY2PJED946ZMIvsX/OSCA-style-guide%2Fpattern)
Creation of the pagination component
Run `npm run storybook`
Resolves #36
=> feat(pagination): add pagination component

src/components/__tests__/nav.test.js, test/cypress/integration/01-layout.test.js
Fix Unit and E2E test failing because of the `nav.js` component update.
Run local tests from the master branch and the test would fail because `nav.js` has been updated.
#<NUMBER>
=> test: fix failing test.

.github/workflows/ci.yml, package-lock.json, package.json, test/cypress/integration/01-layout.test.js
=> feat(): Implement Continuous Integration, Lint and Prettier Check and Coveralls Report.

src/components/seo.js
Reformat code files using `Prettier` and updated `ESlint` rules.
* format code files using `npm run fix:prettier`
`npm run start`
#<NUMBER>
=> refactor: run fix:prettier

.github/workflows/ci.yml
Fix CI workflow - missing lcov file 
#<NUMBER>
=> fix: missing lcov coverage file

src/components/cloudImages.js, src/components/hotels.js, src/pages/travel.js
This PR adds all necessary travel information to the travel guide page
Add contents and images.
`npm run start` and visit the `/travel` page.
N/A
N/A
N/A
=> feat(travel): add travel guide information

src/components/nav.js
Update the layout style of the navigation on mobile
`npm run start`
N/A
N/A
N/A
=> improvement(nav): update nav hamburger layout for mobile

src/components/cloudImages.js, src/components/hotels.js, src/components/restaurants.js, src/pages/travel.js
Update travel guide information
- Update hotels
- Add restaurants
- Clean up
`npm run start`
N/A
N/A
=> improvement(travel-guide): update travel guide information

package-lock.json, package.json
* Chore:  upgrade `cypress` `devdependency` version.
`npm install cypress@4.0.0`
`npm run test:e2e`
#<NUMBER>
=> chore: upgrade cypress 3.7.0 -> 4.0.0

test/cypress/integration/01-layout.test.js
* Fixes failing e2e(cypress) test.
`npm run test:e2e`
#<NUMBER>
=> fix(cypress): failing 01-layout test

src/components/__tests__/nav.test.js
- should have image
- should have 3 children
- header > nav should have 6 nav links
* register
* speaker
* schedule
* travel
* sponsorship
* scholarship
- header > nav should be togglable
* simluate action header > button click
* improve components/nav unit test
* confirm correct number of header > nav links 
* confirm nav > button is toggle-able 
`npm run test:e2e`
#<NUMBER>
=> test(components/nav.test): nav component unit test

src/components/__tests__/breadcrumb.test.js
- should have img tab with src attribute
* src attr should not be empty
- should have text 'test-name'
* add breadcrumb component test
* can fetch img tag src
* should pass props properly
`npm run test:unit -- breadcrumb.test.js`
#<NUMBER>
=> test: components/breadcrumb

src/components/__tests__/cta.test.js
- should have 4 items
- should have texts '800' & 'Attendees'
* add cta component test
* generate 4 dynamic items properly with value and title
`npm run test:unit -- cta.test.js`
#<NUMBER>
=> test: components/cta

src/components/__tests__/nav.test.js, src/components/nav.js, src/components/sustainHead.js, src/pages/sustain-africa.js, test/cypress/integration/01-layout.test.js
Setup structure and agenda
Build sustain page and add agenda
- Add contents
- Add video
- Add agenda
- Add form
`npm run start`
N/A
N/A
=> feat(sustain): build sustain page

src/pages/index.js
=> FIX Festival date metadata

CONTRIBUTING.md, LICENSE, README.md
✅ Closes: 124
This PR updates the doc.
#<NUMBER>
=> docs: ✏️ update docs and contributors guide

src/components/2022/about.js, src/components/2022/slider.js
=> style: 💄 cleanup slider and about index

src/components/2022/nav.js
=> Fix nav items for 2022

src/components/2023/home.js
Add registration ticket options.
=> feat: 🎸 add tickets options

src/components/2023/home.js
Some users report bit.ly failing on some browsers/networks, so we're forced to use direct links. This PR updates the registration links.
=> chore: update registration links

src/components/2023/speakers.js, src/css/style.css
- Implement speakers carousel scrollbar
#<NUMBER>
=> feat: add speakers scrollbar

src/components/2023/cloudImages.js, src/components/2023/nav.js, src/components/2023/speakers.js, src/components/2023/sponsors.js, src/pages/sustain-africa.js
- Implement updates: 
- Speakers
- Sponsors
#206
=> feat: add featured speakers

src/components/2023/footer.js, src/components/2023/gallery.js
This PR fixes the stretched gallery images on mobile that weren't visible in the development mobile inspector.
=> fix: stretched gallery image

src/components/2025/header.js, src/components/2025/nav.js
This PR adds the sponsorship deck and updates some links.
#<NUMBER>
=> feat: add 2025 deck

src/components/2025/header.js
Change dates from June to August
=> Change OSCAFest 2025 dates

src/pages/past-events.js
=> Fix OSCA 2025 dates

src/components/2025/header.js
=> Update sponsorship deck 2025

src/components/2025/header.js
update the cfp link on home page
#<NUMBER>
=> update cfp link

src/components/2025/nav.js
Update the register link
#<NUMBER>
=> update register link

src/components/2025/nav.js, src/pages/speaker-schedule.js
Add the speaker schedule iframe embed on 2025 osca site
#<NUMBER>
=> add speaker schedule

src/pages/sustain-africa.js
Update the agenda of sustain 2025
#<NUMBER>
=> update sustain agenda

src/components/2025/footer.js
Add link to code of conduct and faq page
#<NUMBER>
=> add code of conduct and faq
